name: Django Build + Dependencies

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Automatic requirements.txt for Python Projects
      uses: ryan-rozario/pipreqs-action@v2.0.0
      with:
        PROJECT_PATH: ./PrintPool   #default is the root of the repository
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r PrintPool/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
